#!/bin/bash
PORT=${PORT:-8080}
ECHO=${ECHO:-echo}

RESPONSE="HTTP/1.1 200 OK\r\nConnection: close\r\n\r\n${ECHO}\r\n"

echo "Listening on $PORT"
while true; do
  { echo -en "$RESPONSE" | nc -l "$PORT" &>/dev/null; } || break
done
echo "Quiting..."
