#!/bin/bash
RUNNING=true
PORT=${PORT:-80}
ECHO=${ECHO:-"echo"}
LENGTH=$(echo "$ECHO" | wc -c)

trap quit INT

function quit() {
  echo "Quiting..."
  RUNNING=false
}

echo "Listening on port ${PORT}..."
while ${RUNNING} ; do nc -l -p ${PORT} -c "printf 'HTTP/1.1 200 OK\nContent-Type: text/plain\nContent-Length: ${LENGTH}\nConnection: close\n\n${ECHO}\n'"; done
