---
steps:
  - name: ":shipit: :suspect:"
    branches: master
    concurrency_group: canary/deployment/$PLAIN_ENV
    concurrency: 1
    plugins:
      - docker:
          image: everydayhero/plain-utils:latest
          command: [ deploy, --app, canary, --env, $PLAIN_ENV, --wait ]
          mount-buildkite-agent: false
          always-pull: true
          volumes: false
          shell: false

  - wait

  - name: ":gun:"
    command: "curl -v -f --retry 5 --retry-delay 30 $HEALTH_URL"
    branches: master

