---
steps:
  - name: ":terminal:"
    command: "plain-utils ssh $PLAIN_ENV admin date"
    branches: master

  - name: ":shipit: :suspect:"
    command: "plain-utils deploy-convox canary-$${PLAIN_ENV%%uction}"
    branches: master
    concurrency_group: canary/deployment/convox
    concurrency: 1
    env:
      PLAIN_LOCAL: true

  - name: ":shipit: :suspect:"
    branches: master
    concurrency_group: canary/deployment/ecs
    concurrency: 1
    plugins:
      - docker#v2.1.0:
          image: everydayhero/plain-utils:latest
          command: [ deploy, --app, canary, --env, $PLAIN_ENV, --wait ]
          mount-buildkite-agent: false
          always-pull: true
          volumes: false
          shell: false

  - wait

  - name: ":gun:"
    command: "curl -v -f --retry 5 --retry-delay 30 $HEALTH_URL"
    branches: master

