---
steps:
  - name: ":shipit: Staging"
    command: "bin/buildkite bin/ci deploy staging"
    branches: master

  - name: ":runner: Staging"
    command: "bin/buildkite bin/ci admin-process staging date"
    branches: master

  - wait

  - name: ":gun: Staging"
    command: "curl -f https://canary.everydayhero-staging.io"
    branches: master

  - wait

  - name: ":shipit: Production"
    command: "bin/buildkite bin/ci deploy production"
    branches: master

  - name: ":runner: Production"
    command: "bin/buildkite bin/ci admin-process production date"
    branches: master

  - wait

  - name: ":gun: Production"
    command: "curl -f https://canary.everydayhero.io"
    branches: master
