---
steps:
  - name: ":docker: :construction:"
    command: "bin/buildkite bin/ci build"
    agents:
      queue: build

  - wait

  - name: ":docker: :label: Staging"
    command: "bin/buildkite bin/ci tag staging"
    branches: master

  - name: ":docker: :label: Production"
    command: "bin/buildkite bin/ci tag production"
    branches: master

  - wait

  - name: ":buildkite: Staging"
    command: "bin/buildkite bin/ci initiate-deploy staging"
    branches: master

  - name: ":buildkite: Production"
    command: "bin/buildkite bin/ci initiate-deploy production"
    branches: master
