---
steps:
  - name: ":shipit:"
    command: "bin/buildkite bin/ci deploy $PLAIN_ENV"
    branches: master

  - name: ":runner:"
    command: "bin/buildkite bin/ci admin-process $PLAIN_ENV date"
    branches: master

  - wait

  - name: ":gun:"
    command: "curl -v -f --retry 3 --retry-delay 10 $HEALTH_URL"
    branches: master

