---
steps:
  - name: ":terminal:"
    command: "bin/buildkite bin/ci admin-process $PLAIN_ENV date"
    branches: master

  - name: ":shipit: :suspect:"
    command: "plain-utils deploy-convox canary-${PLAIN_ENV%%uction}"
    branches: master
    concurrency_group: canary/deployment/convox
    concurrency: 1
    env:
      PLAIN_LOCAL: true

  - name: ":shipit: :suspect:"
    command: "plain-utils deploy-ecs canary-${PLAIN_ENV%%uction}"
    branches: master
    concurrency_group: canary/deployment/ecs
    concurrency: 1
    env:
      PLAIN_LOCAL: true

  - wait

  - name: ":gun:"
    command: "curl -v -f --retry 5 --retry-delay 30 $HEALTH_URL"
    branches: master

