---
steps:
  - name: ":docker: :construction:"
    command: "bin/buildkite bin/ci build"
    agents:
      queue: build

  - wait

  - name: ":docker: :label: Staging"
    command: "bin/buildkite bin/ci tag staging"
    branches: master

  - name: ":docker: :label: Production"
    command: "bin/buildkite bin/ci tag Production"
    branches: master

  - wait

  - name: ":shipit: Staging"
    command: "bin/buildkite bin/ci deploy staging"
    branches: master

  - wait

  - name: ":gun: Staging"
    command: "curl -v https://canary.everydayhero-staging.io"
    branches: master

  - wait

  - name: ":shipit: Production"
    command: "bin/buildkite bin/ci deploy production"
    branches: master

  - wait

  - name: ":gun: Production"
    command: "curl -v https://canary.everydayhero.io"
    branches: master
