---
steps:
  - name: ":shipit: Staging"
    command: "bin/buildkite bin/ci deploy staging"
    branches: master

  - wait

  - name: ":gun: Staging"
    command: "curl -v https://canary.everydayhero-staging.io"
    branches: master

  - wait

  - name: ":shipit: Production"
    command: "bin/buildkite bin/ci deploy production"
    branches: master

  - wait

  - name: ":gun: Production"
    command: "curl -v https://canary.everydayhero.io"
    branches: master
