---
steps:
  - name: ":shipit: :goberserk:"
    command: "bin/buildkite bin/ci deploy $PLAIN_ENV"
    branches: master

  - name: ":terminal:"
    command: "bin/buildkite bin/ci admin-process $PLAIN_ENV date"
    branches: master

  - name: ":shipit: :suspect:"
    command: "[ \"$PLAIN_ENV\" = production ] || plain-utils deploy-convox canary-$PLAIN_ENV"
    branches: master

  - wait

  - name: ":gun:"
    command: "curl -v -f --retry 5 --retry-delay 30 $HEALTH_URL"
    branches: master

