---
steps:
  - name: ":docker: :construction:"
    command: "bin/buildkite bin/ci build"
    agents:
      queue: build

  - wait

  - name: ":docker: :label: Staging"
    command: "bin/buildkite bin/ci tag staging"
    branches: master

  - name: ":docker: :label: Production"
    command: "bin/buildkite bin/ci tag production"
    branches: master

  - wait

  - name: ":buildkite: Staging"
    trigger: "canary-deploy-staging"
    branches: master
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"

  - name: ":buildkite: Production"
    trigger: "canary-deploy-production"
    branches: master
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
